import { Text, ScrollView } from 'tamagui';

export function Example() {
  return (
    <ScrollView
      // @ts-expect-error tamagui specific prop
      contentContainerStyle={{ alignItems: 'center' }}
    >
      <Text>Example - first</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example</Text>
      <Text>Example - last</Text>
    </ScrollView>
  );
}
