name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main, dev]  # Adjust according to your branching strategy
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies (root)
        run: npm ci --ignore-scripts
      
      - name: Install dependencies (web app)
        run: cd apps/web && npm ci --ignore-scripts
      
      - name: Build only the web app
        env:
          HUSKY: 0
          HUSKY_SKIP_INSTALL: 1
        run: cd apps/web && npm run build
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: clifford-dejong  # Replace with your preferred Cloudflare Pages project name
          directory: apps/web/out        # The output directory from Next.js static export
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name == 'main' && 'production' || 'preview' }}
