name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main, dev]  # Adjust according to your branching strategy
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      # Set up the entire workspace with Turborepo
      - name: Install dependencies
        run: npm ci --ignore-scripts
        
      # Build the entire monorepo with turbo
      - name: Build web app with monorepo dependencies
        env:
          HUSKY: 0
          HUSKY_SKIP_INSTALL: 1
        run: npm run build -- --filter=web
      
      # List output directory to verify it exists
      - name: List build outputs
        run: ls -la apps/web/out/
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: clifford-dejong  # Replace with your preferred Cloudflare Pages project name
          directory: apps/web/out        # The output directory from Next.js static export
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name == 'main' && 'production' || 'preview' }}
